ember: &defaults
  image: danlynn/ember-cli:2.16.2
  volumes:
    - .:/myapp

npm:
  <<: *defaults
  command: npm

bower:
  <<: *defaults
  command: bower --allow-root

server:
  <<: *defaults
  command: server --watcher polling
  ports:
    - "4200:4200"
    - "49153:49153"
    - "7357:7357"
