import Component from '@ember/component';

export default Component.extend({
  tagName: 'header',
  elementId: 'js-header',

  classNames: ['u-header'],

  classNameBindings: [
    'absBottom:u-header--abs-bottom',
    'absTop:u-header--abs-top',
    'absTop2ndScreen:u-header--abs-top-2nd-screen',
    'changeApperance:u-header--change-appearance',
    'changeLogo:u-header--change-logo',
    'floating:u-header--floating',
    'hashiddenElement:u-header--has-hidden-element',
    'invulnerable:u-header--invulnerable',
    'showHide:u-header--show-hide',
    'static:u-header--static',
    'stickyBottom:u-header--sticky-bottom',
    'stickyTop:u-header--sticky-top',
    'toggleSection:u-header--toggle-section',

    // sm
    'absBottomSm:u-header--abs-bottom--sm',
    'absTopSm:u-header--abs-top--sm',
    'absTop2ndScreenSm:u-header--abs-top-2nd-screen--sm',
    'changeApperanceSm:u-header--change-appearance--sm',
    'changeLogoSm:u-header--change-logo--sm',
    'floatingSm:u-header--floating--sm',
    'hashiddenElementSm:u-header--has-hidden-element--sm',
    'invulnerableSm:u-header--invulnerable--sm',
    'showHideSm:u-header--show-hide--sm',
    'staticSm:u-header--static--sm',
    'stickyBottomSm:u-header--sticky-bottom--sm',
    'stickyTopSm:u-header--sticky-top--sm',
    'toggleSectionSm:u-header--toggle-section--sm',

    // md
    'absBottomMd:u-header--abs-bottom--md',
    'absTopMd:u-header--abs-top--md',
    'absTop2ndScreenMd:u-header--abs-top-2nd-screen--md',
    'changeApperanceMd:u-header--change-appearance--md',
    'changeLogoMd:u-header--change-logo--md',
    'floatingMd:u-header--floating--md',
    'hashiddenElementMd:u-header--has-hidden-element--md',
    'invulnerableMd:u-header--invulnerable--md',
    'showHideMd:u-header--show-hide--md',
    'staticMd:u-header--static--md',
    'stickyBottomMd:u-header--sticky-bottom--md',
    'stickyTopMd:u-header--sticky-top--md',
    'toggleSectionMd:u-header--toggle-section--md',

    // lg
    'absBottomLg:u-header--abs-bottom--lg',
    'absTopLg:u-header--abs-top--lg',
    'absTop2ndScreenLg:u-header--abs-top-2nd-screen--lg',
    'changeApperanceLg:u-header--change-appearance--lg',
    'changeLogoLg:u-header--change-logo--lg',
    'floatingLg:u-header--floating--lg',
    'hashiddenElementLg:u-header--has-hidden-element--lg',
    'invulnerableLg:u-header--invulnerable--lg',
    'showHideLg:u-header--show-hide--lg',
    'staticLg:u-header--static--lg',
    'stickyBottomLg:u-header--sticky-bottom--lg',
    'stickyTopLg:u-header--sticky-top--lg',
    'toggleSectionLg:u-header--toggle-section--lg',

    // xl
    'absBottomXl:u-header--abs-bottom--xl',
    'absTopXl:u-header--abs-top--xl',
    'absTop2ndScreenXl:u-header--abs-top-2nd-screen--xl',
    'changeApperanceXl:u-header--change-appearance--xl',
    'changeLogoXl:u-header--change-logo--xl',
    'floatingXl:u-header--floating--xl',
    'hashiddenElementXl:u-header--has-hidden-element--xl',
    'invulnerableXl:u-header--invulnerable--xl',
    'showHideXl:u-header--show-hide--xl',
    'staticXl:u-header--static--xl',
    'stickyBottomXl:u-header--sticky-bottom--xl',
    'stickyTopXl:u-header--sticky-top--xl',
    'toggleSectionXl:u-header--toggle-section--xl',
  ],

  attributeBindings: [
    'fixMoment:data-header-fix-moment',
    'fixEffect:data-header-fix-effect'
  ],

  // className Bindings
  absBottom: false,
  absTop: false,
  absTop2ndScreen: false,
  changeApperance: false,
  changeLogo: false,
  floating: false,
  hashiddenElement: false,
  invulnerable: false,
  showHide: false,
  static: false,
  stickyBottom: false,
  stickyTop: false,
  toggleSection: false,

  // sm
  absBottomSm: false,
  absTopSm: false,
  absTop2ndScreenSm: false,
  changeApperanceSm: false,
  changeLogoSm: false,
  floatingSm: false,
  hashiddenElementSm: false,
  invulnerableSm: false,
  showHideSm: false,
  staticSm: false,
  stickyBottomSm: false,
  stickyTopSm: false,
  toggleSectionSm: false,

  // md
  absBottomMd: false,
  absTopMd: false,
  absTop2ndScreenMd: false,
  changeApperanceMd: false,
  changeLogoMd: false,
  floatingMd: false,
  hashiddenElementMd: false,
  invulnerableMd: false,
  showHideMd: false,
  staticMd: false,
  stickyBottomMd: false,
  stickyTopMd: false,
  toggleSectionMd: false,

  // lg
  absBottomLg: false,
  absTopLg: false,
  absTop2ndScreenLg: false,
  changeApperanceLg: false,
  changeLogoLg: false,
  floatingLg: false,
  hashiddenElementLg: false,
  invulnerableLg: false,
  showHideLg: false,
  staticLg: false,
  stickyBottomLg: false,
  stickyTopLg: false,
  toggleSectionLg: false,

  // xl
  absBottomXl: false,
  absTopXl: false,
  absTop2ndScreenXl: false,
  changeApperanceXl: false,
  changeLogoXl: false,
  floatingXl: false,
  hashiddenElementXl: false,
  invulnerableXl: false,
  showHideXl: false,
  staticXl: false,
  stickyBottomXl: false,
  stickyTopXl: false,
  toggleSectionXl: false,

  //attribute Bindings
  fixMoment: 500,
  fixEffect: 'slide',

});
